routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.dashboard');
});

Route::get('/transaksi-offline', function () {
    return view('pages.offline.transaksi');
});

// Route::get('/input-produk', function () {
//     return view('pages.warehouse.input-produk');
// });

Route::get('/product-size', 'ProdukController@get_product_size')->name('product_size');

Route::resource('produk', ProdukController::class);

// Route::get('/lists-produk', 'ProdukController@index')->name('lists-produk');

// Route::post('/submit-produk', 'ProdukController@store')->name('submit-produk');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;

    protected $table = 'sys_produk';

    protected $primaryKey = 'produk_id';
    protected $timestamps = false;

    protected $fillable = [
        'product_category_name',
        'product_name',
        'product_price',
        'product_size',
        'product_stock',
    ];
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Models\Size;
use App\Models\Produk;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\Validator;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {              
        // Langsung ke datatable with Ajax
        if (request()->ajax()) {
            
            $data = DB::table('sys_produk')->orderBy('produk_id', 'desc')->get();

            return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function($row){
                    $btn = '<a href="javascript:void(0)" data-id="'.$row->produk_id.'" class="edit editProduk btn btn-primary btn-sm mr-2">View</a>';
                    $btn .= '<a href="javascript:void(0)" data-id="'.$row->produk_id.'" class="delete deleteProduk btn btn-danger btn-sm">Delete</a>';
                        return $btn;    
                })
                ->rawColumns(['action'])
                ->editColumn('produk_sku_id', function($row){
                    return $row->produk_sku_id ? $row->produk_sku_id : '-'; 
                })
                ->editColumn('product_price', function($row){
                    return number_format($row->product_price,2,',','.');
                })
                // ->make(true)
                ->toJson();
        }

        return view ('pages.warehouse.input-produk');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product_size = Size::all();
        return view('pages.master.produk.add', ['product_size' => $product_size]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {                
        $validator = Validator::make($request->all(), [
            'category_product'   => 'required',
            'name_product'       => 'required',
            'price_product'      => 'required',
            'price_sale_product' => 'required',
            'tags_product'       => 'required',
            'qty_product'        => 'required|numeric|min:1'
        ]); 

        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }
        
        // To string
        $json = json_encode($request->tags_product);
        dd($json);

        $produk_variant = implode(" ",$request->produk_variant);

        $post = Produk::create([
            'product_category_name'     => $request->kategori, 
            'product_name'              => $request->produk_name,
            'product_price'             => $request->produk_price,
            'product_size'              => $produk_variant,
            'product_stock'             => $request->produk_qty
        ]);

        return redirect()->route('produk')->with('success', 'Data Tersimpan!');
    }

    /**
    * Display the specified resource.
    *
    * @param int $id
    * @return \Illuminate\Http\Response
    */
    public function show($id)
    {
        
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param int $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        $produk = Produk::find($id);
        return response()->json($produk);
    }

    /**
    * Update the specified resource in storage.
    *
    * @param \Illuminate\Http\Request $request
    * @param int $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id)
    {
        
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param int $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        
    }

    public function get_product_size(){
        if (request()->ajax()) {
            $product_size = Size::all()->toJson();
        }
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public $title;
    public function __construct($title = null){
        $this->title = $title ?? 'Bijak Jawa';
    }

    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/master/produk/add.blade.php
<x-app-layout title="Input Produk">
    <x-header-page>
        Input Produk
    </x-header-page>

    <div class="row">
        <div class="col-sm-7">
            <div class="card" style="border-radius: 7px;">
                <div class="card-header">
                    <h4>General</h4>
                </div>
                <div class="card-body">
                    <form class="form-floating" method="POST" action="{{ route('produk.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label class="col-form-label ml-3 for=" tanggal_input">Tanggal
                                Input </label>
                            <div class="col-sm-12">
                                <input id="tanggal_input" name="tanggal_input" type="text" class="form-control"
                                    value="12 September 2005" disabled>
                                <div class="invalid-feedback">
                                    Tanggal Input
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label ml-3" for="category_product">Category
                                Produk</label>
                            <div class="col-sm-12">
                                <input id="category_product" name="category_product" type="text"
                                    class="form-control @error('category_product') is-invalid @enderror"
                                    value="{{ old('category_product') }}">
                                @error('category_product')
                                <div class="invalid-feedback">
                                    <span class="text-danger">{{ $message }}</span>
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label ml-3" for="name_product">Nama
                                Produk</label>
                            <div class="col-sm-12">
                                <input id="name_product" name="name_product" type="text"
                                    class="form-control mb-2 @error('name_product') is-invalid @enderror"
                                    value="{{ old('name_product')}}">
                                @error('name_product')
                                <div class="invalid-feedback">
                                    <span class="text-danger">{{ $message }}</span>
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label ml-3" for="price_product">Harga
                                Produk (HPP)</label>
                            <div class="col-sm-12">
                                <input id="price_product" name="price_product" type="text"
                                    class="form-control @error('price_product') is-invalid @enderror"
                                    value="{{ old('price_product') }}" placeholder="0" value="0">
                                @error('price_product')
                                <div class="invalid-feedback">
                                    <span class="text-danger">{{ $message }}</span>
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label ml-3" for="price_sale_product">Harga
                                Jual</label>
                            <div class="col-sm-12">
                                <input id="price_sale_product" name="price_sale_product" type="text"
                                    class="form-control @error('price_sale_product') is-invalid @enderror"
                                    value="{{ old('price_sale_product') }}" placeholder="0" value="0">
                                @error('price_sale_product')
                                <div class="invalid-feedback">
                                    <span class="text-danger">{{ $message }}</span>
                                </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label ml-3">Variant Size</label>
                            <div class="input-group col-sm-12">
                                <input type="text" class="form-control" placeholder="Add variant"
                                    aria-label="Recipient's username" aria-describedby="basic-addon2"
                                    id="input_variant">
                                <div class="input-group-append">
                                    <button class="btn btn-info" type="button" id="add_variant">Add</button>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                <table class="table table-responsive" id="table_variant_parent" style="display: none;">
                                    <thead>
                                        <tr style="text-align:center;">
                                            <th>Action</th>
                                            <th width="15%">Variant</th>
                                            <th>Stock</th>
                                            <th>Price(Rp.)</th>
                                            <th>Price Selling(Rp.)</th>
                                            <th>Disc(%)</th>
                                            <th>Weight(gr)</th>
                                        </tr>
                                    </thead>
                                    <tbody id="table_variant">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer text-right col-sm-12 pr-0">
                            <button class="btn btn-primary" type="submit">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="card">
                <div class="card-header">
                    <h4>Supplier</h4>
                </div>
                <div class="card-body">

                </div>
            </div>
        </div>
    </div>

    <!-- Javascript -->
    @push('custom-js')
    <script src="{{ asset('assets/js/produk/produk-add.js') }}"></script>
    @endpush
</x-app-layout>